# Generated by Django 3.0.5 on 2021-04-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('date', models.DateField()),
                ('booleon', models.BooleanField()),
                ('float', models.FloatField()),
            ],
        ),
    ]
