# Generated by Django 3.0.5 on 2021-04-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='branch',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='courses',
            name='credit',
            field=models.CharField(default=None, max_length=2),
        ),
        migrations.AddField(
            model_name='courses',
            name='dis',
            field=models.CharField(default=None, max_length=800),
        ),
    ]
