# Generated by Django 3.0.5 on 2021-04-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210425_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='booleon',
        ),
        migrations.AddField(
            model_name='courses',
            name='fac1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courses',
            name='fac2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courses',
            name='fac3',
            field=models.BooleanField(default=False),
        ),
    ]
