# Generated by Django 3.0.5 on 2021-04-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210425_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='float',
            new_name='ttime',
        ),
        migrations.AddField(
            model_name='courses',
            name='ctype',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='courses',
            name='fac1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='courses',
            name='fac2',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='courses',
            name='fac3',
            field=models.CharField(max_length=10),
        ),
    ]
