# Generated by Django 3.0.5 on 2021-04-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210426_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='fac1',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='courses',
            name='fac2',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='courses',
            name='fac3',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
