# Generated by Django 3.0.5 on 2021-04-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210426_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='img',
            field=models.ImageField(upload_to='pic'),
        ),
    ]
